---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openstack-csi
resources:
  - "namespace.yaml"
  - "source.yaml"
  - "helmrelease.yaml"
secretGenerator:
  - name: openstack-csi-values-base
    type: Opaque
    files:
      - hardened.yaml=helm-values/hardened-values-2.33.1.yaml
    options:
      disableNameSuffixHash: true
