---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "../namespace.yaml"
  - "source.yaml"
  - "../helmrelease.yaml"
secretGenerator:
  - name: headlamp-values-base
    namespace: headlamp
    type: Opaque
    files:
      - values.yaml=../helm-values/values-0.35.0.yaml
    options:
      disableNameSuffixHash: true
