---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
secretGenerator:
  - name: kube-prometheus-stack-values-override
    namespace: observability
    type: Opaque
    files: [override.yaml=helm-values/override_values.yaml]
    options:
      disableNameSuffixHash: true
