namespace: ingress-nginx

resources:
  - "./namespace.yaml"
  - "./helmrelease.yaml"

secretGenerator:
  - name: ingress-nginx-values
    type: Opaque
    files:
      - helm-values/hardened_values_4.13.0.yaml
      - helm-values/override_values.yaml
    options:
      disableNameSuffixHash: true
