---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "namespace.yaml"
  - "source.yaml"
  - "helmrelease.yaml"
secretGenerator:
  - name: loki-distributed-values-base
    type: Opaque
    files:
      - hardened.yaml=helm-values/hardened-values-v0.80.5.yaml
    options:
      disableNameSuffixHash: true