apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
secretGenerator:
  - name: ingress-nginx-values-override
    namespace: ingress-nginx
    type: Opaque
    files:
      - override.yaml=helm-values/override_values.yaml
    options:
      disableNameSuffixHash: true
