---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgres-operator
resources: [./namespace.yaml, ./source.yaml, ./helmrelease.yaml]
secretGenerator:
  - name: postgres-operator-values-base
    type: Opaque
    files: [hardened.yaml=helm-values/hardened_values_1.14.0.yaml]
    options:
      disableNameSuffixHash: true
