---
opentelemetry-operator:
  enabled: true
  manager:
    collectorImage:
      repository: ghcr.io/opencenter-cloud/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-k8s
      tag: "0.136.0"
    image:
      repository: ghcr.io/opencenter-cloud/open-telemetry/opentelemetry-operator/opentelemetry-operator
      tag: "0.136.0"
  kubeRBACProxy:
    enabled: true
    image:
      repository: ghcr.io/opencenter-cloud/brancz/kube-rbac-proxy
      tag: v0.19.1
  imagePullSecrets:
    - name: ghcr-secret
defaultCRConfig:
  enabled: true
  mode: DaemonSet
  serviceAccount: "otel-collector-sa"
  image:
    repository: ghcr.io/opencenter-cloud/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-k8s
    pullPolicy: IfNotPresent
    tag: "0.136.0"
