---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - "./catalog-source.yaml"
  - "./keycloak-operator-sa.yaml"
patches:
  - target:
      group: operators.coreos.com
      version: v1alpha1
      kind: Subscription
      name: keycloak-subscription
      namespace: keycloak
    path: subscription-private-catalog.yaml
