---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "../sources/opentelemetry.yaml"
  - "./helmrelease.yaml"

secretGenerator:
  - name: opentelemetry-kube-stack-values-base
    type: Opaque
    files: [hardened.yaml=helm-values/hardened-values-v0.11.1.yaml]
    options:
      disableNameSuffixHash: true
