---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "disallow-capabilities-strict.yaml"
  - "disallow-capabilities.yaml"
  - "disallow-host-namespaces.yaml"
  - "disallow-host-path.yaml"
  - "disallow-host-ports.yaml"
  - "disallow-host-process.yaml"
  - "disallow-privilege-escalation.yaml"
  - "disallow-privileged-containers.yaml"
  - "disallow-proc-mount.yaml"
  - "disallow-selinux.yaml"
  - "require-run-as-non-root-user.yaml"
  - "require-run-as-nonroot.yaml"
  - "restrict-apparmor-profiles.yaml"
  - "restrict-seccomp-strict.yaml"
  - "restrict-seccomp.yaml"
  - "restrict-sysctls.yaml"
  - "restrict-volume-types.yaml"
