---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/namespace.yaml
  - resources/longhorn-encrypted-storageclass.yaml
  - resources/longhorn-multi-attach-storageclass.yaml
  - resources/longhron-general-storageclass.yaml
  - resources/helmrelease.yaml

secretGenerator:
  - name: longhorn-values-base
    namespace: longhorn-system
    type: Opaque
    files:
      - hardened.yaml=helm-base-overrides/hardened-values-v0.0.1.yaml
    options:
      disableNameSuffixHash: true
