global:
  hub: "ghcr.io/opencenter-cloud/istio"
  # Default tag for Istio images.
  tag: 1.28.3
  imagePullSecrets:
    - ghcr-secret
autoscaleMin: 2
pilot:
  env:
    PILOT_ENABLE_GATEWAY_API_STATUS: false
    PILOT_ENABLE_GATEWAY_API: false
