---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
resources:
  - "namespace.yaml"
  - "../source.yaml"
  - "helmrelease.yaml"
secretGenerator:
  - name: istio-base-values-base
    type: Opaque
    files:
      - hardened.yaml=helm-values/hardened-values-1.24.2.yaml
    options:
      disableNameSuffixHash: true
