---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx-base
  namespace: flux-system
spec:
  dependsOn:
    - name: sources
      namespace: flux-system
  interval: 5m
  retryInterval: 1m
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: opencenter-ingress-nginx
    namespace: flux-system
  path: applications/base/managed-services/ingress-nginx
  targetNamespace: ingress-nginx
  prune: true
  wait: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: ingress-nginx
      namespace: ingress-nginx
  commonMetadata:
    labels:
      app.kubernetes.io/part-of: ingress-nginx
      app.kubernetes.io/managed-by: flux
      opencenter/managed-by: opencenter

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx-override
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 1m
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./applications/overlays/demo-cluster/services/ingress-nginx
  targetNamespace: ingress-nginx
  prune: true
  wait: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: ingress-nginx
      namespace: ingress-nginx
  commonMetadata:
    labels:
      app.kubernetes.io/part-of: ingress-nginx
      app.kubernetes.io/managed-by: flux
      opencenter/managed-by: opencenter
