---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "namespace.yaml"
  - "source.yaml"
  - "helmrelease.yaml"
secretGenerator:
  - name: rbac-manager-values-base
    type: Opaque
    files: [hardened.yaml=helm-values/hardened-values-1.21.1.yaml]
    options:
      disableNameSuffixHash: true
