---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "../../sources/opentelemetry.yaml"
  - "../helmrelease.yaml"
secretGenerator:
  - name: opentelemetry-kube-stack-values-base
    namespace: observability
    type: Opaque
    files:
      - values.yaml=../helm-values/values-v0.11.1.yaml
    options:
      disableNameSuffixHash: true
