namespace: keycloak

resources:
  - "./namespace.yaml"
  - "./helmrelease.yaml"
  - "./backendtlspolicy.yaml"
  - "./httproute.yaml"

secretGenerator:
  - name: keycloak-values
    namespace: keycloak
    type: Opaque
    files:
      - hardened.yaml=helm-values/hardened_values_25.2.0.yaml
      - override.yaml=helm-values/override_values.yaml
    options:
      disableNameSuffixHash: true
