---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "../namespace.yaml"
  - "source.yaml"
  - "../helmrelease.yaml"
secretGenerator:
  - name: cert-manager-values-base
    type: Opaque
    files:
      - values.yaml=../helm-values/values-v1.18.2.yaml
    options:
      disableNameSuffixHash: true
