---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-snapshotter
resources:
  [
    "./namespace.yaml",
    "github.com/kubernetes-csi/external-snapshotter//client/config/crd?ref=v8.2.1",
    "github.com/kubernetes-csi/external-snapshotter//deploy/kubernetes/snapshot-controller?ref=v8.2.1",
  ]
