---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "../../sources/kube-prometheus-stack.yaml"
  - "../helmrelease.yaml"
secretGenerator:
  - name: kube-prometheus-stack-values-base
    namespace: observability
    type: Opaque
    files:
      - values.yaml=../helm-values/values-77.6.0.yaml
      - alertmanager-overrides.yaml=../helm-values/alertmanager-overrides.yaml
      - prometheus-overrides.yaml=../helm-values/prometheus-overrides.yaml
    options:
      disableNameSuffixHash: true
