---
global:
  imagePullSecrets:
    - name: ghcr-secret
image:
  repository: ghcr.io/opencenter-cloud/quay.io/jetstack/cert-manager-controller
  tag: v1.18.2
webhook:
  image:
    repository: ghcr.io/opencenter-cloud/quay.io/jetstack/cert-manager-webhook
    tag: v1.18.2
cainjector:
  image:
    repository: ghcr.io/opencenter-cloud/quay.io/jetstack/cert-manager-cainjector
    tag: v1.18.2
acmesolver:
  image:
    repository: ghcr.io/opencenter-cloud/quay.io/jetstack/cert-manager-acmesolver
    tag: v1.18.2
startupapicheck:
  image:
    repository: ghcr.io/opencenter-cloud/quay.io/jetstack/cert-manager-startupapicheck
    tag: v1.18.2
