apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - ../namespace.yaml
    - ../community/source.yaml
    - ../helmrelease.yaml
components:
    - ../components/enterprise
secretGenerator:
    - name: cert-manager-values-base
      namespace: cert-manager
      type: Opaque
      files:
        - values.yaml=../helm-values/values-v1.18.2.yaml
      options:
        disableNameSuffixHash: true
