---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ./opencenter-gateway-api.yaml
  - ./opencenter-cert-manager.yaml
  - ./opencenter-olm.yaml
  - ./opencenter-olm-config.yaml
  - ./opencenter-ingress-nginx.yaml
  - ./opencenter-sealed-secrets.yaml
  - ./opencenter-kube-prometheus-stack.yaml
