---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: opencenter-kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 5m
  url: ssh://git@github.com/rackerlabs/openCenter.git
  ref:
    branch: main
  secretRef:
    name: opencenter-base
