---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "../namespace.yaml"
  - "source.yaml"
  - "../helmrelease.yaml"
secretGenerator:
  - name: rbac-manager-values-base
    namespace: rbac-system
    type: Opaque
    files:
      - values.yaml=../helm-values/values-1.21.1.yaml
    options:
      disableNameSuffixHash: true
