---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "./namespace.yaml"
  - "./source.yaml"
  - "./helmrelease.yaml"

secretGenerator:
  - name: psmdb-operator-values-base
    type: Opaque
    files: [hardened.yaml=helm-values/hardened-values-v1.21.1.yaml]
    options:
      disableNameSuffixHash: true