---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [./namespace.yaml, ./source.yaml, ./helmrelease.yaml]

secretGenerator:
  - name: falco-values-base
    type: Opaque
    files: [hardened.yaml=helm-values/hardened-values-6.2.5.yaml]
    options:
      disableNameSuffixHash: true
