---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "../helmrelease.yaml"
  - "../../../global/enterprise/source.yaml"
patches:
  - path: patch-helmrelease-source.yaml
    target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: loki
      namespace: observability
secretGenerator:
  - name: loki-values-base
    namespace: observability
    type: Opaque
    files:
      - values.yaml=../helm-values/values-v6.45.2.yaml
    options:
      disableNameSuffixHash: true
  - name: loki-values-enterprise
    namespace: observability
    type: Opaque
    files:
      - hardened-enterprise.yaml=./helm-values/hardened-values-v6.45.2.yaml
    options:
      disableNameSuffixHash: true
