---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "../namespace.yaml"
  - "../helmrelease.yaml"
  - "../../global/enterprise/source.yaml"
patches:
  - path: patch-helmrelease-source.yaml
    target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: istio
      namespace: istio-system
secretGenerator:
  - name: istio-values-base
    namespace: istio-system
    type: Opaque
    files:
      - values.yaml=../helm-values/values-1.28.3.yaml
    options:
      disableNameSuffixHash: true
  - name: istio-values-enterprise
    namespace: istio-system
    type: Opaque
    files:
      - hardened-enterprise.yaml=./helm-values/hardened-values-1.28.3.yaml
    options:
      disableNameSuffixHash: true
