apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - ../namespace.yaml
    - ../community/source.yaml
    - ../helmrelease.yaml
components:
    - ../components/enterprise
secretGenerator:
    - name: envoy-gateway-api-values-base
      namespace: envoy-gateway-system
      type: Opaque
      files:
        - values.yaml=../helm-values/values-v0.0.0.yaml
      options:
        disableNameSuffixHash: true
