---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "../helmrelease.yaml"
  - "../../../global/enterprise/source.yaml"
patches:
  - path: patch-helmrelease-source.yaml
    target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: kube-prometheus-stack
      namespace: observability
secretGenerator:
  - name: kube-prometheus-stack-values-base
    namespace: observability
    type: Opaque
    files:
      - values.yaml=../helm-values/values-77.6.0.yaml
      - alertmanager-overrides.yaml=../helm-values/alertmanager-overrides.yaml
      - prometheus-overrides.yaml=../helm-values/prometheus-overrides.yaml
    options:
      disableNameSuffixHash: true
  - name: kube-prometheus-stack-values-enterprise
    namespace: observability
    type: Opaque
    files:
      - hardened-enterprise.yaml=./helm-values/hardened-values-77.6.0.yaml
      - hardened-alertmanager-overrides.yaml=./helm-values/alertmanager-overrides.yaml
      - hardened-prometheus-overrides.yaml=./helm-values/prometheus-overrides.yaml
    options:
      disableNameSuffixHash: true
