---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx-shared
  namespace: flux-system
spec:
  dependsOn:
    - name: helm-sources
      namespace: flux-system
  interval: 1m
  path: ./applications/base/managed-services/ingress-nginx/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  dependsOn:
    - name: ingress-nginx-shared
      namespace: flux-system
  interval: 1m
  path: ./applications/overlays/delta/managed-services/ingress-nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: ingress-nginx
  wait: true
