apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sources.yaml
  - gateway-api.yaml
  - cert-manager.yaml
  - ingress-nginx.yaml
  - sealed-secrets.yaml
  - keycloak.yaml
  - gateway.yaml
