---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "../../10-operator/"
  - "./catalog-source.yaml"
patches:
  - target:
      group: operators.coreos.com
      version: v1alpha1
      kind: Subscription
      name: keycloak-subscription
      namespace: keycloak
    path: subscription-private-catalog.yaml
