apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
    - ../../../../global/enterprise/source.yaml
patches:
    - target:
        kind: HelmRepository
        name: kyverno
      patch: |-
        $patch: delete
        apiVersion: source.toolkit.fluxcd.io/v1
        kind: HelmRepository
        metadata:
          name: kyverno
    - target:
        group: helm.toolkit.fluxcd.io
        version: v2
        kind: HelmRelease
        name: kyverno
      patch: |-
        - op: replace
          path: /spec/chart/spec/sourceRef/name
          value: opencenter-cloud
secretGenerator:
    - name: kyverno-values-enterprise
      namespace: kyverno
      type: Opaque
      files:
        - hardened-enterprise.yaml=../../enterprise/helm-values/hardened-values-3.6.0.yaml
      options:
        disableNameSuffixHash: true
