---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "../namespace.yaml"
  - "../helmrelease.yaml"
  - "../../global/enterprise/source.yaml"
patches:
  - path: patch-helmrelease-source.yaml
    target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: metallb
      namespace: metallb-system
secretGenerator:
  - name: metallb-values-base
    namespace: metallb-system
    type: Opaque
    files:
      - values.yaml=../helm-values/values-0.15.2.yaml
    options:
      disableNameSuffixHash: true
  - name: metallb-values-enterprise
    namespace: metallb-system
    type: Opaque
    files:
      - hardened-enterprise.yaml=./helm-values/hardened-values-0.15.2.yaml
    options:
      disableNameSuffixHash: true
