apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - namespace.yaml
    - community/source.yaml
    - helmrelease.yaml
secretGenerator:
    - name: metallb-values-base
      namespace: metallb-system
      type: Opaque
      files:
        - values.yaml=helm-values/values-0.15.2.yaml
      options:
        disableNameSuffixHash: true
