apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
    - ../../../global/enterprise/source.yaml
    - ../../enterprise/otel-collector-sa.yaml
patches:
    - target:
        kind: HelmRepository
        name: opentelemetry
      patch: |-
        $patch: delete
        apiVersion: source.toolkit.fluxcd.io/v1
        kind: HelmRepository
        metadata:
          name: opentelemetry
    - target:
        group: helm.toolkit.fluxcd.io
        version: v2
        kind: HelmRelease
        name: opentelemetry-kube-stack
      patch: |-
        - op: replace
          path: /spec/chart/spec/sourceRef/name
          value: opencenter-cloud
secretGenerator:
    - name: opentelemetry-kube-stack-values-enterprise
      namespace: observability
      type: Opaque
      files:
        - hardened-enterprise.yaml=./helm-values/hardened-values-v0.11.1.yaml
      options:
        disableNameSuffixHash: true
