apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - "./bitnami.yaml"
  - "./envoyproxy.yaml"
  - "./ingress-nginx.yaml"
  - "./jetstack.yaml"
  - "./sealed-secrets.yaml"
