---
# Global settings
global:
  imagePullSecrets:
    - name: ghcr-secret
  # Override image-specific values directly if a global override is not desired.
  images:
    envoyGateway:
      # This is the full image name including the hub, repo, and tag.
      image: ghcr.io/opencenter-cloud/docker.io/envoyproxy/gateway:v1.5.1
    ratelimit:
      # This is the full image name including the hub, repo, and tag.
      image: ghcr.io/opencenter-cloud/docker.io/envoyproxy/ratelimit:e74a664a
deployment:
  annotations: {}
  envoyGateway:
    image:
      # if both this and global.imageRegistry are specified, this has to include both registry and repository explicitly, eg docker.io/envoyproxy/gateway
      repository: "ghcr.io/opencenter-cloud/docker.io/envoyproxy/gateway"
      tag: "v1.5.1"
