apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - namespace.yaml
    - community/source.yaml
    - helmrelease.yaml
secretGenerator:
    - name: kyverno-values-base
      namespace: kyverno
      type: Opaque
      files:
        - values.yaml=helm-values/values-3.6.0.yaml
      options:
        disableNameSuffixHash: true
