apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - ../namespace.yaml
    - ../community/source.yaml
    - ../helmrelease.yaml
components:
    - ../components/enterprise
secretGenerator:
    - name: postgres-operator-values-base
      namespace: postgres-operator
      type: Opaque
      files:
        - values.yaml=../helm-values/values-1.14.0.yaml
      options:
        disableNameSuffixHash: true
