---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "../namespace.yaml"
  - "source.yaml"
  - "../helmrelease.yaml"
secretGenerator:
  - name: istio-values-base
    namespace: istio-system
    type: Opaque
    files:
      - values.yaml=../helm-values/values-1.28.3.yaml
    options:
      disableNameSuffixHash: true
