---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: observability
spec:
  interval: 5m
  timeout: 10m
  driftDetection:
    mode: enabled
  install:
    createNamespace: true
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: 0
      remediateLastFailure: false
  targetNamespace: observability
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 77.6.0
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: observability
  valuesFrom:
    - kind: Secret
      name: kube-prometheus-stack-values-base
      valuesKey: hardened.yaml
#    - kind: Secret
#      name: kube-prometheus-stack-values-base
#      valuesKey: alerting-rules-overrides.yaml
#    - kind: Secret
#      name: kube-prometheus-stack-values-base
#      valuesKey: alertmanager-overrides.yaml
    - kind: Secret
      name: kube-prometheus-stack-values-base
      valuesKey: prometheus-overrides.yaml
    - kind: Secret
      name: kube-prometheus-stack-values-override
      valuesKey: override.yaml
      optional: true
