---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [./namespace.yaml, ./source.yaml, ./helmrelease.yaml]
secretGenerator:
  - name: kube-prometheus-stack-values-base
    namespace: observability
    type: Opaque
    files:
      - hardened.yaml=helm-values/hardened-values-v0.0.1.yaml
      - alertmanager-overrides.yaml=helm-values/alertmanager-overrides.yaml
      - prometheus-overrides.yaml=helm-values/prometheus-overrides.yaml
    options:
      disableNameSuffixHash: true
