apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sealed-secrets
secretGenerator:
  - name: sealed-secrets-values-override
    type: Opaque
    files:
      - override.yaml=helm-values/override_values.yaml
    options:
      disableNameSuffixHash: true
