namespace: gateway-api

resources:
  - "./namespace.yaml"
  - "./helmrelease.yaml"

secretGenerator:
  - name: envoy-gateway-api-values
    namespace: gateway-api
    type: Opaque
    files:
      - hardened.yaml=helm-values/hardened_values_v0.0.0.yaml
      - override.yaml=helm-values/override_values.yaml
    options:
      disableNameSuffixHash: true
