apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: envoy-gateway-system
resources:
  - "./networkpolicy.yaml"
secretGenerator:
  - name: envoy-gateway-api-values-override
    namespace: envoy-gateway-system
    type: Opaque
    files:
      - override.yaml=helm-values/override_values.yaml
    options:
      disableNameSuffixHash: true
