---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: catalog-operator
      namespace: olm
    path: patch-catalog-operator-images.yaml
  - target:
      group: operators.coreos.com
      version: v1alpha1
      kind: CatalogSource
      name: operatorhubio-catalog
      namespace: olm
    path: patch-operatorhubio-catalog-image.yaml
