---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: alert-proxy
secretGenerator:
  - name: alert-proxy-values-override
    type: Opaque
    files: [override.yaml=helm-values/override_values.yaml]
    options:
      disableNameSuffixHash: true
