apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
    - ../../../global/enterprise/source.yaml
patches:
    - target:
        kind: HelmRepository
        name: jetstack
      patch: |-
        $patch: delete
        apiVersion: source.toolkit.fluxcd.io/v1
        kind: HelmRepository
        metadata:
          name: jetstack
    - target:
        group: helm.toolkit.fluxcd.io
        version: v2
        kind: HelmRelease
        name: cert-manager
      patch: |-
        - op: replace
          path: /spec/chart/spec/sourceRef/name
          value: opencenter-cloud
secretGenerator:
    - name: cert-manager-values-enterprise
      namespace: cert-manager
      type: Opaque
      files:
        - hardened-enterprise.yaml=../../enterprise/helm-values/hardened-values-v1.18.2.yaml
      options:
        disableNameSuffixHash: true
