auth:
    #ENC[AES256_GCM,data:laaNXT4WSE/eCepOziT2mQKx97Xffnl+/U7XiYCZkVsyhM54dTFuwZb0XzMneYAmogK6,iv:uphcJQRVfh2KtrvhHDEmqa21i5Zlv41GEpUVLjwUWWo=,tag:D5fhc0UllMUm/abv99YArQ==,type:comment]
    #ENC[AES256_GCM,data:fw==,iv:DzW8gOGMFNMzthnpPKh0xXnW5VTunSYIN6a75/+krW4=,tag:+i/07mBblAlB/Ifiqvvadw==,type:comment]
    adminUser: ENC[AES256_GCM,data:39ne9tw=,iv:wVQJk9Di5VIjDrngHUtcOJrFT5VsOTwxq7PdTBPIdj8=,tag:hZmLJGL61hSC5gul1ib4pw==,type:str]
    #ENC[AES256_GCM,data:nNfsTZN7sdcKmh1S0ZZjT/+l1bh2P1JSHZIhxVATLBjai50shG+L3rYbXMGqbhlQIHL7CLXHRZwZ9mJEd1DAdHyrtst6PzRiJbw6xA==,iv:rPaat+boHZdIOO0+a4k2l4aC7n9Z5N4ptCRNp2jX+Uw=,tag:c9SjkO/9c5HEL/y/h0d/ng==,type:comment]
    #ENC[AES256_GCM,data:jQ==,iv:2BvN7btjgOwzK8dmTt0jNB7D5nzT9SYIFEQkSLNcMJ0=,tag:iUx0NJ5hMB11NjE6LAmLLQ==,type:comment]
    adminPassword: ENC[AES256_GCM,data:7WIckOpVIqCA+P9YZqKeUjMvSp8=,iv:BvGwO/0cVecSnIajjG1W7gfF5VS7LISWW956NhhYGJY=,tag:CUHUkt7/MJqY2+b9WwhSeg==,type:str]
postgresql:
    enabled: ENC[AES256_GCM,data:lefFQQ==,iv:jfV5QlnVOaXSkrUesEWRAViAL6zHBWrzxoHIqYjByG8=,tag:OyjLjGfTK8Xt53lRPE2lVg==,type:bool]
    auth:
        postgresPassword: ENC[AES256_GCM,data:3aHodU542xpuGeuRQzeE4Qi2IOk=,iv:zvU0jgoqgg068I7HNU/6UjcjsuO9+/H0zgv5PMCWSmI=,tag:Xkjq2wMAJcDfb6w/hYQCuQ==,type:str]
        username: ENC[AES256_GCM,data:+q3n/iCb9WaS0rs=,iv:Vp9YU+tJiq5qKF4fnzMUVjshZ5VusH7sp3kecCahGDg=,tag:F1qLDRnL3YQz9+YiDVMxFA==,type:str]
        password: ENC[AES256_GCM,data:uB/9OXVPiRztMq8UAtEB2dN6llc=,iv:CDOzj0FPbNEnaVD1OkT1TL3UZ1uCf7NLTHJE39GoyOQ=,tag:rxvlV5MY7PZW0l4LZjdcKw==,type:str]
        database: ENC[AES256_GCM,data:T+uX5bVXgvVE6bE5GAU3Nw==,iv:2r3ebiv3lTnQEZlY/Yw5zDy7D+v1AcPDi2IAGWvhUi0=,tag:Mw7ODTcWwkdxykgKdOYiQQ==,type:str]
        existingSecret: ""
        secretKeys:
            userPasswordKey: ENC[AES256_GCM,data:aPlehBBoAoE=,iv:N349ngCOvxw8tZ3drmx7vMkP+ragJcDOOlAdVwsvEtM=,tag:5/pQZTf/Xi5+qlz0cR5Lwg==,type:str]
    architecture: ENC[AES256_GCM,data:NQ/a6YXAWmQw9FQ=,iv:CuB/Moej+bwo5LmlrgkFESt9a35CHUYmJ55mVJVcj2I=,tag:IYZywE5sAH6og2vOZyOCVQ==,type:str]
tls:
    enabled: ENC[AES256_GCM,data:E9/XfA==,iv:ax+uVEiVcy8mnHFQp6abW4NAxBiy4vjWmHOtzNOG26E=,tag:BOw54INhe0HKcBBYjWhJnw==,type:bool]
    usePemCerts: ENC[AES256_GCM,data:VL7l8w==,iv:ZvOvP44UlfpY0pDx99/E9802BOeyoQmtpeB5IwOK0Uo=,tag:AqfgJoxEJlS0rq9n2lIA6A==,type:bool]
    autoGenerated:
        enabled: ENC[AES256_GCM,data:aoOGjQ==,iv:EumstscmtT/sER1pxdI+K1LJAFWqUouMrL5QVndvJNQ=,tag:kkaeYMzRZ+8zu5PQ6hPjNQ==,type:bool]
        engine: ENC[AES256_GCM,data:uX+MVi9x46eQt/gV,iv:fvbipsNADfRwYZH852JgAT//vmq+eDCR01S4e/RMVzI=,tag:mNw+l5wcRpxeZOD1zfFiIA==,type:str]
        certManager:
            existingIssuer: ENC[AES256_GCM,data:b5XaR/NZiHWGWZDw,iv:5aqtU6zYiI2ncpCzfqnvbhfz/e3h5mvaMaUY5o1w20E=,tag:MeV5KezfPHmerSbqGNxQMA==,type:str]
            existingIssuerKind: ENC[AES256_GCM,data:MQMV5v/LYZsieC1pfQ==,iv:N9xAO66pnt2TmDVkVMYomjH5cvLmkiK0BEJRauW+2oo=,tag:TmU0j9fPFgDNlWa6u607KA==,type:str]
            keySize: ENC[AES256_GCM,data:2wnvBg==,iv:nQlX57U74K7xmIK7Y9cHIGZDzRJP7l982ANANBT+jLo=,tag:4FsMZv2I4gD2IA9PsHwRVg==,type:int]
            keyAlgorithm: ENC[AES256_GCM,data:jXab,iv:wTSEm6YeK0NhDUDsdDjKJxUgKYsOEqOKEnn9gSoCMLU=,tag:cPH5RaadaEFqMwiAtmazQg==,type:str]
            duration: ENC[AES256_GCM,data:W3EpSAk=,iv:vMFXgBDIKdm3xxOtdMSi/Jb0T69RvNfKYktAwvWeDNc=,tag:3viQp2991y3M/R+i6H6RTA==,type:str]
            renewBefore: ENC[AES256_GCM,data:7Bo2Zg==,iv:mhB4WlVPCM2LuhNVR/mu7jLXMwjJmRM/xMwAODb9R/c=,tag:ZcxENdm5d3sZ8f8AbkBO3A==,type:str]
resourcesPreset: ENC[AES256_GCM,data:XSVBUMPE,iv:hrQTVZfIBk5OrJQHlqIn6m9FLH3HrO3rO8fi+dowRkM=,tag:qZvr6KxTXWo/1Or0I/oGRg==,type:str]
hostnameStrict: ENC[AES256_GCM,data:cIsiHQ==,iv:LSfIh0hvvgTnTcqUfluAT8kM4JANhhqYJlSt7aJteXY=,tag:RpaxrS91f0yLQb935gSn6Q==,type:bool]
sops:
    age:
        - recipient: age1ydr20ml7gdda4pkq5exe4amr426xtxnkwl2sdtt2zlxnu2jhg90qe2u4qk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMzhVWUZ3cTVlTjh5UlVU
            RmJlRkY0UFNSYlBGdHZ2RzVSQlZDdnd5QUNJCkQ3WU0yL1NpSG1LQWN0YWV0WUNY
            bmhqNXVNUGhDMmprT0JiMW5hOUNEMDAKLS0tIEx0R0pUSlQ3OGR3djA4eTF6QkFH
            clAxeWNCWmUwM1NXYi8xVWRZZXRDU0EKsw/UcmFBNITMRisn4i3OogeZJj1Zp/0O
            BzrZMEHd2FMzxihQ4fCOS1T4aMf348UJYXyIgeOiKdWppT4eJva9OQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-31T14:49:52Z"
    mac: ENC[AES256_GCM,data:DSeWeU6/55GcAcMYx6El3/YqtZ7jfm9NbjC0OKE1rccrLp4be5cNmhhcWPunze6Q6R06VkZ/Kl2+jCt4lqMcsL45roLLDdJ2LAn8FLl/qw3YCt9VyHMSK6lFWuzk39tM+dW8ugAv95oke39QZ08oikowRAmCvwoA4e0gWZ+dCho=,iv:qCYJs808mT7rEftsfCgva+A1xCBeJDz5ptymcSodlwQ=,tag:Y3SD1Cgkp943kILNZ8SOow==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
