---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [./namespace.yaml, ./source.yaml, ./helmrelease.yaml]

secretGenerator:
  - name: envoy-gateway-api-values-base
    namespace: envoy-gateway-system
    type: Opaque
    files: [hardened.yaml=helm-values/hardened-values-v0.0.0.yaml]
    options:
      disableNameSuffixHash: true
