namespace: sealed-secrets

resources:
  - "./namespace.yaml"
  - "./helmrelease.yaml"

secretGenerator:
  - name: sealed-secrets-values
    type: Opaque
    files:
      - helm-values/hardened_values_2.17.3.yaml
      - helm-values/override_values.yaml
    options:
      disableNameSuffixHash: true
